---
title: "gsbe-data-prep"
author: "bbl"
format:
  html:
    code-fold: true
toc: true
editor: visual
---

```{r setup}
#| include: false

library(dplyr)
library(tidyr)
library(ggplot2)
theme_set(theme_bw())
library(sf)
library(rnaturalearth)
library(readr)
library(terra)
library(lubridate)
```

## SRDB

```{r read-srdb}
#| fig-width: 12

read_csv("data-srdb/srdb-data.csv", show_col_types = FALSE) %>% 
    select(Author, Study_midyear, YearsOfData, 
           Latitude, Longitude, Elevation, Manipulation, 
           Biome, Ecosystem_type, Ecosystem_state, 
           Rs_annual, Rs_growingseason) %>% 
    filter(!is.na(Longitude), !is.na(Latitude), !is.na(Study_midyear)) %>% 
    filter(!is.na(Rs_growingseason) | !is.na(Rs_annual)) %>% 
    filter(Manipulation == "None") ->
    srdb

message(nrow(srdb), " rows of data")

message("There are ", sum(srdb$YearsOfData > 1, na.rm = TRUE), " multi-year observations")

srdb %>% 
    filter(YearsOfData == 1) ->
    srdb
message(nrow(srdb), " final rows of data")

world <- ne_coastline()
srdb_annual <- srdb %>% filter(is.na(Rs_annual))
ggplot(world) + 
    geom_sf() + 
    geom_point(data = srdb_annual, 
               aes(x = Longitude, y = Latitude, color = Biome),
               na.rm = TRUE) + 
    ggtitle(paste0("SRDB Rs_annual N=", nrow(srdb_annual)))

srdb_growingseason <- srdb %>% filter(is.na(Rs_growingseason))
ggplot(world) + 
    geom_sf() + 
    geom_point(data = srdb_growingseason, 
               aes(x = Longitude, y = Latitude, color = Biome),
               na.rm = TRUE) + 
    ggtitle(paste0("SRDB Rs_growingseason N=", nrow(srdb_growingseason)))
```

```{r srdb-prep}
#| fig-width: 12

set.seed(12)
srdb %>% 
    slice_sample(n = 20) -> 
    srdb_sample

srdb_sample %>% 
    select(Longitude, Latitude) ->
    coords

ggplot(world) + 
    geom_sf() + 
    geom_point(data = srdb_sample, 
               aes(x = Longitude, y = Latitude, color = Biome),
               size = 4,
               na.rm = TRUE) + 
    ggtitle(paste0("SRDB subsample N=", nrow(srdb_sample)))
```

## SPEI

We are using the ERA5–Drought dataset; see Keune et al. 2025 <https://www.nature.com/articles/s41597-025-04896-y>.

```{r read-spei}
#| fig-height: 6
#| fig-width: 10

files <- list.files(path = "data-spei/", pattern = "*.nc$", full.names = TRUE)
message("Processing ", length(files), " SPEI files...")
spei_list <- list()
for(f in files) {
    x <- suppressWarnings(terra::rast(f)) 
    dat <- terra::extract(x, coords)
    dat$time <- terra::time(x)
    spei_list[[f]] <- dat
}
bind_rows(spei_list) %>% 
    as_tibble() -> spei
spei$Biome <- srdb_sample$Biome[spei$ID]

ggplot(spei, aes(x = SPEI12)) + geom_histogram(bins = 50) + 
    facet_wrap(~Biome) +
    ggtitle("SPEI12")

ggplot(spei, aes(time, SPEI12, color = Biome, group = ID)) + 
    geom_line() + 
    facet_grid(Biome~.) + 
    theme(legend.position = "none") +
    ggtitle("SPEI12")

# Summarise to annual, January-March, and July-September
spei %>% 
    mutate(Year = year(time), 
           Month = month(time)) %>% 
    arrange(time) %>% 
    group_by(Biome, ID, Year) %>% 
    summarise(SPEI12jas = mean(SPEI12[7:9]),
              SPEI12jfm = mean(SPEI12[1:3]),
              SPEI12 = mean(SPEI12),
              .groups = "drop") ->
    spei_annual

ggplot(spei_annual, aes(Year, SPEI12, color = Biome, group = ID)) + 
    geom_line() + 
    facet_grid(Biome~.) + 
    theme(legend.position = "none") +
    ggtitle("SPEI12 - annual mean")

message("Merging into SRDB data...")
srdb_sample$ID <- seq_len(nrow(srdb_sample))
srdb_sample$Year <- floor(srdb_sample$Study_midyear)
srdb_sample$Year1 <- srdb_sample$Year - 1

spei_annual %>% select(ID, Year, SPEI12) -> spei_annual_join
spei_annual_join %>% rename(SPEI12_y1 = SPEI12) -> spei_annual_join_y1

srdb_sample %>% 
    left_join(spei_annual_join, by = c("ID" = "ID", "Year" = "Year")) %>% 
    left_join(spei_annual_join_y1, by = c("ID" = "ID", "Year1" = "Year")) ->
    srdb_sample

ggplot(srdb_sample, aes(x = SPEI12_y1)) + geom_histogram(bins = 50) + 
    facet_wrap(~Biome) +
    ggtitle("SPEI12 previous year")

ggplot(srdb_sample, aes(Year, SPEI12_y1, color = Biome)) + 
    geom_point() + 
    facet_grid(Biome~.) + 
    theme(legend.position = "none") +
    ggtitle("SPEI12 previous year")
```

## Climate data

When you click the **Render** button a document will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
1 + 1
```

## Reproducibility

```{r}
#| echo: false

sessionInfo()
```
