---
title: "gsbe-data"
author: "bbl"
format:
  html:
    code-fold: true
toc: true
editor: visual
---

```{r setup}
#| include: false

library(dplyr)
library(tidyr)
library(ggplot2)
theme_set(theme_bw())
library(readr)
library(lubridate)

dat <- read_csv("srdb_joined_data.csv", show_col_types = FALSE)

message(nrow(dat), " rows of data")

dat %>% 
    filter(is.na(Rs_growingseason) | (Rs_growingseason > 0 & Rs_growingseason < 20)) %>% 
    filter(is.na(Rs_annual) | (Rs_annual > 0 & Rs_annual < 4000)) %>% 
    filter(is.na(Rh_annual) | (Rh_annual > 0 & Rh_annual < 2000)) %>% 
    replace_na(list(Biome = "Unknown")) ->
    dat_filtered

```

## Independent variable distribution

We have three potential independent variables – `Rs_annual` (annual soil respiration), `Rh_annual` (annual heterotrophic respiration), and `Rs_growingseason` (mean growing season soil respiration) – and expect their distributions to be non-normal.

```{r}
#| fig-width: 10
#| fig-height: 8

dat_filtered %>% 
    select(Rs_annual, Rh_annual, Rs_growingseason) %>% 
    pivot_longer(everything()) %>% 
    filter(!is.na(value), value > 0) %>% 
    rename(none = value) %>% 
    mutate(log = log(none), sqrt = sqrt(none)) %>% 
    
    pivot_longer(-name, names_to = "Transformation") %>% 
    ggplot(aes(value, color = Transformation)) + 
    geom_density() +
    facet_wrap(~ name + Transformation, scales = "free")

dat_filtered %>% 
    mutate(sqrt_Rs_annual = sqrt(Rs_annual),
           sqrt_Rh_annual = sqrt(Rh_annual),
           sqrt_Rs_growingseason = sqrt(Rs_growingseason)) ->
    dat_filtered

```

We have a winner: `sqrt()`!

## Dataset overview

```{r read-data}
#| fig-width: 10
#| fig-height: 8

dat_filtered %>% 
    select(Biome, Ecosystem_type, sqrt_Rs_annual, sqrt_Rh_annual, sqrt_Rs_growingseason,
           Tair, Tsoil_lev1, VWC_lev1, Precip, LAI_high, 
           MODIS_NPP, MODIS_GPP) %>% 
    pivot_longer(Tair:MODIS_GPP, names_to = "covariate_name", values_to = "covariate_value") %>%
    pivot_longer(sqrt_Rs_annual:sqrt_Rs_growingseason) %>% 
    ggplot(aes(value, covariate_value, color = Biome)) + 
        facet_grid(covariate_name ~ name, scales = "free") +
        geom_point(na.rm = TRUE)

dat_filtered %>% 
    filter(!Biome == "Semi-arid", !Biome == "Unknown") %>% 
    select(Biome, Ecosystem_type, sqrt_Rs_annual, 
           Tair, Tsoil_lev1, VWC_lev1, Precip, LAI_high) %>% 
    pivot_longer(Tair:LAI_high, names_to = "covariate_name", values_to = "covariate_value") %>% 
    ggplot(aes(sqrt_Rs_annual, covariate_value, color = Biome)) + 
        facet_grid(covariate_name ~ Biome, scales = "free") +
        geom_point(na.rm = TRUE)
 
stn <- as.factor(dat_filtered$Soil_type_number)
nst <- length(unique(stn))
dat_filtered %>% 
    select(sqrt_Rs_growingseason, sqrt_Rs_annual, sqrt_Rh_annual) %>% 
    pairs(col = hcl.colors(nst, "Temps")[stn])

```

## Analysis1

```{r}
#| eval: false


fit_lm <- function(x) {} # fit linear model for a dataset; i.v. in first column
fit_rf <- function(x) {} # fit random forest model

do_k_fold <- function(x, k = 10) {
    if(!all(complete.cases(x))) {
        stop("x should not have any NAs at this stage!")
    }
    
    groups <- sample.int(n = k, size = nrow(x), replace = TRUE)
    training_r2 <- rep.int(NA_real_, k)
    validation_r2 <- rep.int(NA_real_, k)
    for(i in seq_len(k)) {
        x_validation <- x[groups == i,]
        x_training <- x[groups != i,]
        message("\tk-fold ", i, ": training has ", nrow(x_training), 
                "; validation has ", nrow(x_validation))
        
        m <- lm(speed ~ dist, data = x_training)
        training_r2[i] <- summary(m)$r.squared
        message("\t\tTraining R2 = ", round(training_r2[i], 3))
        pred <- predict(m, newdata = x_validation)
        rss <- sum((pred - x_validation$speed) ^ 2)
        tss <- sum((x_validation$speed - mean(x_validation$speed)) ^ 2)
        validation_r2[i] <- 1 - rss / tss
        message("\t\tValidation R2 = ", round(validation_r2[i], 3))
    }
    m_overall <- lm(speed ~ dist, data = x)
    message("\tAll-data R2 = ", summary(m)$r.squared)
    message("\tMean training validation R2 = ", mean(training_r2))
    message("\tMean validation validation R2 = ", mean(validation_r2))
} # compute fit statistics using k-fold


# compute distances between points if using spatial RF
# fit ranger::ranger() or spatialRF::rf()
# predict and compute R2

# fit_lm()
# predict and compute R2

# return fit statistics by model type

# These are the three most common fluxes recorded in SRDB
iv_set <- c("sqrt_Rs_annual", "sqrt_Rh_annual", "sqrt_Rs_growingseason")
# These are from Table 1 of Keune et al. (2025)
# https://www.nature.com/articles/s41597-025-04896-y
spei_cutoffs <- c(-1.5, -1.0, 0.0)
predictors <- c("Longitude", "Latitude", # hmmmmm
                "Ecosystem_type", 
                "SPEI12", "SPEI12_y1", 
                "MODIS_NPP", "MODIS_GPP",
                "Tair", "Precip",
                "Tsoil_lev1", "Tsoil_lev2", "VWC_lev1", "VWC_lev2", 
                "LAI_high", "Soil_type_name")

do_full_analysis <- function(x, iv_set, predictors, spei_cutoffs) {
    results <- list()
    for(iv in iv_set) {
        
        # Remove other potential independent variables
        this_x <- x[c(iv, predictors)]
        # Complete cases only
        this_x <- this_x[complete.cases(this_x),]
        
        for(spei_cut in spei_cutoffs) {
            message("---------------------------------------------")
            message("iv = ", iv, ", spei_cut = ", spei_cut)
            message("\tn = ", nrow(this_x))
            
            # identify observations not currently in a drought but that
            # WERE in a drought the previous year
            # PBE = potential Birch effect
            this_x$PBE = with(this_x, SPEI12 > 0 & SPEI12_y1 <= spei_cut)
            message("\tPBE = ", sum(this_x$PBE))
            
            results[[paste(iv, spei_cut)]] <- do_k_fold(this_x)
        }
    }
}


# rescale predictors
# complete.cases
# compute variable inflation or other correlated predictors metric

# loop over iv_set and spei_cutoff_values:


# - compute PBE flag
    dat_filtered %>% 
        # identify observations not in a drought but WERE in a drought
        # PBE = potential Birch effect
        mutate(PBE = SPEI12 > 0 & SPEI12_y1 <= -1) ->
        dat_pbe
# - for each model type
# --- fit model and calculate PBE effect
# --- call do_k_fold
# --- save fit data associated with this iv and cutoff value

m <- lm(sqrt_Rs_annual ~ Tair + Tsoil_lev1 + Tsoil_lev2 + 
            VWC_lev1 + I(VWC_lev1 ^ 2) + VWC_lev2 ^ 2 + I(VWC_lev2 ^ 2) + 
            MODIS_GPP + MODIS_NPP + 
            Ecosystem_type * PBE, 
        data = dat_pbe)
m_reduced <- MASS::stepAIC(m, trace = FALSE)
summary(m_reduced)

library(car)
car::Anova(m_reduced, type = "III")
```

## Reproducibility

```{r}
#| echo: false

sessionInfo()
```
